### PR TITLE
 Remove deprecated dependencies, update others dependencies, and convert class to function component

### PR DESCRIPTION
**Pull request by nabedkhan**
Update: Remove deprecated dependencies, update others dependencies, and convert component to function component

1. Replace babel-core with @babel/core
2. Replace babel-plugin-transform-object-rest-spread with @babel/plugin-proposal-object-rest-spread
3. Replace babel-preset-env with @babel/preset-env
4. Replace babel-preset-react with @babel/preset-react
5. Replace rollup-plugin-babel with @rollup/plugin-babel
6. Replace rollup-plugin-node-resolve with @rollup/plugin-node-resolve
7. Replace rollup-plugin-uglify with @rollup/plugin-terser

File Edited:

1. gulpfile.js
2. .babelrc
3. rollup.config.js
4. src/react-apexcharts.jsx
5. src/react-apexcharts.test.js

### CODE REVIEW

**Comment by junedchhipa** [comment]
There is a conflict in package-lock.json. Please fix it and the PR looks good to me.
Thanks for the contribution @nabedkhan

**Comment by nabedkhan** [comment]
I have fixed the conflict. Now you can merge it. @junedchhipa

**Comment by junedchhipa** [comment]
There is still a conflict in example/package-lock.json

**Comment by junedchhipa** [comment]
Thanks, I will review once again and see how it goes

**Review by junedchhipa — APPROVED** [review]

**Pull request merged**
